/* DAMIRA TEXTILE — veri katmanı
 * Yeni koleksiyon eklemek: COLLECTIONS'a kayıt, DESENLER'e img + çeviriler.
 * Görseller items/ klasöründedir; filtre/arama otomatik çalışır.
 */
(function (global) {
  'use strict';

  const COLLECTIONS = [
    { id: 'monaco',    img: 'items/ChatGPT%20Image%2029%20Tem%202026%2012_26_41.jpg', tr: 'Monaco',    en: 'Monaco',    fr: 'Monaco' },
    { id: 'corsica',   img: 'items/ChatGPT%20Image%206%20Tem%202026%2014_11_22.jpg', tr: 'Korsika',   en: 'Corsica',   fr: 'Corse' },
    { id: 'vendee',    img: 'items/ChatGPT%20Image%2029%20Tem%202026%2015_31_42.jpg', tr: 'Vendée',    en: 'Vendée',    fr: 'Vendée' },
    { id: 'oleron',    img: 'items/ChatGPT%20Image%2029%20Tem%202026%2012_34_37.jpg', tr: 'Île d’Oléron', en: 'Île d’Oléron', fr: 'Île d’Oléron' },
    { id: 'baiedesomme', img: 'items/ChatGPT%20Image%2030%20Tem%202026%2012_41_28.jpg', tr: 'Baie de Somme', en: 'Baie de Somme', fr: 'Baie de Somme' },
    { id: 'marseille', img: 'items/ChatGPT%20Image%208%20Tem%202026%2011_46_44.jpg', tr: 'Marsilya',  en: 'Marseille', fr: 'Marseille' },
    { id: 'fortboyard', img: 'items/ChatGPT%20Image%208%20Tem%202026%2013_49_26.jpg', tr: 'Fort Boyard', en: 'Fort Boyard', fr: 'Fort Boyard' }
  ];

  /* Desenler: koleksiyon id'si + görsel yolu + dillerde (ad, açıklama, etiket).
   * Aynı görsel birden çok varyant için kullanılabilir (görsel çakışması olmadan). */
  const PRODUCTS = [
    /* MONACO */
    { id: 'monaco-casino', coll: 'monaco', img: 'items/ChatGPT%20Image%2029%20Tem%202026%2012_26_41.jpg',      tr: { n: 'Monte-Carlo', d: 'Kumarhanenin cephesi, çeşmesi ve palmiyeleri; altın tonlu gece ışıltısı.', t: 'Monument' },
      en: { n: 'Monte-Carlo', d: 'The casino façade with fountain and palms, a golden glow at dusk.', t: 'Monument' },
      fr: { n: 'Monte-Carlo', d: 'La façade du casino, sa fontaine et ses palmiers, dorée au crépuscule.', t: 'Monument' } },
    { id: 'monaco-port', coll: 'monaco', img: 'items/ChatGPT%20Image%2029%20Tem%202026%2012_30_02.jpg',
      tr: { n: 'Port Hercule', d: 'Yatlar, deniz ve terakota çatılar; Akdeniz limanı manzarası.', t: 'Paysage' },
      en: { n: 'Port Hercule', d: 'Yachts, sea and terracotta roofs, a Mediterranean harbour view.', t: 'Landscape' },
      fr: { n: 'Port Hercule', d: 'Yachts, mer et toits de terracotta, vue sur le port méditerranéen.', t: 'Paysage' } },
    { id: 'monaco-palais', coll: 'monaco', img: 'items/ChatGPT%20Image%2029%20Tem%202026%2012_34_37.jpg',
      tr: { n: 'Palais Princier', d: 'Prens Sarayı’nın kuleleri ve meydanı; tarihi taş dokusu.', t: 'Monument' },
      en: { n: 'Prince’s Palace', d: 'The palace towers and cobbled square, historic stone texture.', t: 'Monument' },
      fr: { n: 'Palais Princier', d: 'Les tours du palais et sa place pavée, texture de pierre historique.', t: 'Monument' } },
    { id: 'monaco-terrasse', coll: 'monaco', img: 'items/ChatGPT%20Image%2029%20Tem%202026%2012_37_58.jpg',
      tr: { n: 'Jardin Exotique', d: 'Lavanta, servi ağaçları ve deniz manzarası; bahçe terası.', t: 'Jardin' },
      en: { n: 'Exotic Garden', d: 'Lavender, cypress and a sea view, a garden terrace.', t: 'Garden' },
      fr: { n: 'Jardin Exotique', d: 'Lavande, cyprès et vue sur la mer, une terrasse de jardin.', t: 'Jardin' } },

    /* CORSICA */
    { id: 'corsica-moor', coll: 'corsica', img: 'items/ChatGPT%20Image%206%20Tem%202026%2011_49_58.jpg',
      tr: { n: 'Testa Mora', d: 'Korsika’nın simgesi Mağribi başı; siyah-beyaz yüksek kontrast.', t: 'Emblème' },
      en: { n: 'Testa Mora', d: 'The Moor’s head, Corsica’s emblem, in high-contrast black and white.', t: 'Emblem' },
      fr: { n: 'Testa Mora', d: 'La tête de Maure, emblème de la Corse, en noir et blanc contrasté.', t: 'Emblème' } },
    { id: 'corsica-olives', coll: 'corsica', img: 'items/ChatGPT%20Image%206%20Tem%202026%2012_03_20.jpg',
      tr: { n: 'Olivier', d: 'Hasır sepette siyah ve yeşil zeytinler; zeytin dalıyla.', t: 'Nature' },
      en: { n: 'Olive Grove', d: 'Black and green olives in a wicker basket, with olive branch.', t: 'Nature' },
      fr: { n: 'Olivier', d: 'Olives noires et vertes dans un panier en osier, avec branche.', t: 'Nature' } },
    { id: 'corsica-bonifacio', coll: 'corsica', img: 'items/ChatGPT%20Image%206%20Tem%202026%2014_05_24.jpg',
      tr: { n: 'Bonifacio', d: 'Kayalıklar üzerinde terakota çatılar ve deniz; zeytin dalı eşliğinde.', t: 'Paysage' },
      en: { n: 'Bonifacio', d: 'Terracotta roofs on cliffs above the sea, with an olive branch.', t: 'Landscape' },
      fr: { n: 'Bonifacio', d: 'Toits de terracotta sur les falaises, avec branche d’olivier.', t: 'Paysage' } },
    { id: 'corsica-tour', coll: 'corsica', img: 'items/ChatGPT%20Image%206%20Tem%202026%2014_11_22.jpg',
      tr: { n: 'Tour Génoise', d: 'Ceneviz kulesi, deniz ufku ve tek kuş; zeytin dalıyla.', t: 'Monument' },
      en: { n: 'Genoese Tower', d: 'The Genoese tower, sea horizon and a single bird, with olive branch.', t: 'Monument' },
      fr: { n: 'Tour Génoise', d: 'La tour génoise, horizon marin et un oiseau, avec branche d’olivier.', t: 'Monument' } },
    { id: 'corsica-citrons', coll: 'corsica', img: 'items/ChatGPT%20Image%206%20Tem%202026%2014_37_21.jpg',
      tr: { n: 'Citronniers', d: 'Sepette limonlar, çiçekler ve yapraklar; Akdeniz tazeliği.', t: 'Nature' },
      en: { n: 'Lemon Grove', d: 'Lemons in a basket with blossom and leaves, Mediterranean freshness.', t: 'Nature' },
      fr: { n: 'Citronniers', d: 'Citrons dans un panier, fleurs et feuilles, fraîcheur méditerranéenne.', t: 'Nature' } },

    /* VENDÉE */
    { id: 'vendee-window', coll: 'vendee', img: 'items/ChatGPT%20Image%2029%20Tem%202026%2015_27_43.jpg',
      tr: { n: 'La Fenêtre', d: 'Mavi panjurlu pencere, beyaz perdeler ve çiçekli sepetli bisiklet.', t: 'Scène' },
      en: { n: 'The Window', d: 'A window with blue shutters, white curtains and a flower-basket bicycle.', t: 'Scene' },
      fr: { n: 'La Fenêtre', d: 'Une fenêtre aux volets bleus, rideaux blancs et vélo à panier fleuri.', t: 'Scène' } },
    { id: 'vendee-bicyclette', coll: 'vendee', img: 'items/ChatGPT%20Image%2029%20Tem%202026%2015_31_42.jpg',
      tr: { n: 'Bicyclette', d: 'Çiçek dolu hasır sepetli mavi bisiklet, kırsal Vendée sahnesi.', t: 'Scène' },
      en: { n: 'Bicyclette', d: 'A blue bicycle with a wicker basket full of flowers, rural Vendée.', t: 'Scene' },
      fr: { n: 'Bicyclette', d: 'Un vélo bleu au panier d’osier fleuri, scène rurale vendéenne.', t: 'Scène' } },
    { id: 'vendee-poissons', coll: 'vendee', img: 'items/ChatGPT%20Image%2030%20Tem%202026%2012_32_00.jpg',
      tr: { n: 'Trois Poissons', d: 'Üç renkli balık, yatay çizgili denizcilik amblemi.', t: 'Marin' },
      en: { n: 'Three Fishes', d: 'Three coloured fishes, a striped nautical emblem.', t: 'Marine' },
      fr: { n: 'Trois Poissons', d: 'Trois poissons colorés, emblème marin rayé.', t: 'Marin' } },
    { id: 'vendee-goeland', coll: 'vendee', img: 'items/ChatGPT%20Image%2030%20Tem%202026%2012_38_22.jpg',
      tr: { n: 'Goéland', d: 'Direk üzerinde martı, dalgalı deniz ve kumlu sahil.', t: 'Marin' },
      en: { n: 'Seagull', d: 'A gull on a post, rolling sea and sandy shore.', t: 'Marine' },
      fr: { n: 'Goéland', d: 'Un goéland sur un poteau, mer ondulée et plage de sable.', t: 'Marin' } },

    /* ÎLE D'OLÉRON */
    { id: 'oleron-phare', coll: 'oleron', img: 'items/ChatGPT%20Image%2030%20Tem%202026%2012_37_07.jpg',
      tr: { n: 'Phare de Chassiron', d: 'Kırmızı fenerli beyaz deniz feneri, mavi deniz üzerinde.', t: 'Monument' },
      en: { n: 'Chassiron Lighthouse', d: 'A white lighthouse with a red lantern over a blue sea.', t: 'Monument' },
      fr: { n: 'Phare de Chassiron', d: 'Un phare blanc au feu rouge, au-dessus d’une mer bleue.', t: 'Monument' } },
    { id: 'oleron-phare-2', coll: 'oleron', img: 'items/ChatGPT%20Image%2030%20Tem%202026%2010_47_05.jpg',
      tr: { n: 'Phare d’Oléron', d: 'Deniz feneri, kırmızı korkuluklu galeri ve dalgalı mavi deniz.', t: 'Monument' },
      en: { n: 'Oléron Lighthouse', d: 'A lighthouse with a red-railed gallery over a rolling blue sea.', t: 'Monument' },
      fr: { n: 'Phare d’Oléron', d: 'Un phare, galerie à rambarde rouge, au-dessus d’une mer bleue.', t: 'Monument' } },
    { id: 'oleron-poissons', coll: 'oleron', img: 'items/ChatGPT%20Image%2030%20Tem%202026%2012_19_07.jpg',
      tr: { n: 'Poissons d’Oléron', d: 'Üç balık, mavi-kırmızı-açık mavi denizcilik deseni.', t: 'Marin' },
      en: { n: 'Oléron Fishes', d: 'Three fishes in blue, red and light blue, a nautical pattern.', t: 'Marine' },
      fr: { n: 'Poissons d’Oléron', d: 'Trois poissons bleu, rouge et bleu clair, motif marin.', t: 'Marin' } },

    /* BAIE DE SOMME */
    { id: 'somme-cabanes', coll: 'baiedesomme', img: 'items/ChatGPT%20Image%2030%20Tem%202026%2012_41_28.jpg',
      tr: { n: 'Cabanes de Plage', d: 'İskele üzerinde üç renkli plaj kulübesi, önünde martı.', t: 'Scène' },
      en: { n: 'Beach Huts', d: 'Three colourful beach huts on a boardwalk, a gull in front.', t: 'Scene' },
      fr: { n: 'Cabanes de Plage', d: 'Trois cabanes de plage colorées sur pilotis, un goéland devant.', t: 'Scène' } },
    { id: 'somme-cabanes-4', coll: 'baiedesomme', img: 'items/ChatGPT%20Image%2030%20Tem%202026%2012_41_39.jpg',
      tr: { n: 'Quatre Cabanes', d: 'Dört plaj kulübesi yan yana, üzerinde uçan martı.', t: 'Scène' },
      en: { n: 'Four Huts', d: 'Four beach huts in a row, a gull flying above.', t: 'Scene' },
      fr: { n: 'Quatre Cabanes', d: 'Quatre cabanes de plage alignées, goéland en vol.', t: 'Scène' } },
    { id: 'somme-phoque', coll: 'baiedesomme', img: 'items/ChatGPT%20Image%2030%20Tem%202026%2012_46_13.jpg',
      tr: { n: 'Phoque', d: 'Kumda dinlenen benekli fok, deniz ve kum katmanlarıyla.', t: 'Nature' },
      en: { n: 'The Seal', d: 'A spotted seal resting on the sand, layered sea and shore.', t: 'Nature' },
      fr: { n: 'Phoque', d: 'Un phoque tacheté posé sur le sable, mer et plage en couches.', t: 'Nature' } },
    { id: 'somme-poissons', coll: 'baiedesomme', img: 'items/ChatGPT%20Image%2030%20Tem%202026%2013_33_18.jpg',
      tr: { n: 'Poissons de Somme', d: 'Üç balık, lacivert tek renk çizim deseni.', t: 'Marin' },
      en: { n: 'Somme Fishes', d: 'Three fishes, a single navy line-drawn pattern.', t: 'Marine' },
      fr: { n: 'Poissons de Somme', d: 'Trois poissons, motif dessiné en bleu marine.', t: 'Marin' } },

    /* MARSEILLE */
    { id: 'marseille-basilique', coll: 'marseille', img: 'items/ChatGPT%20Image%208%20Tem%202026%2011_46_44.jpg',
      tr: { n: 'Notre-Dame de la Garde', d: 'Altın Meryem heykeliyle bazilika, sulu boya yumuşaklığında.', t: 'Monument' },
      en: { n: 'Notre-Dame de la Garde', d: 'The basilica with its golden Virgin, soft watercolour tone.', t: 'Monument' },
      fr: { n: 'Notre-Dame de la Garde', d: 'La basilique et sa Vierge dorée, en aquarelle douce.', t: 'Monument' } },
    { id: 'marseille-vieuxport', coll: 'marseille', img: 'items/ChatGPT%20Image%2029%20Tem%202026%2015_24_04.jpg',
      tr: { n: 'Vieux-Port', d: 'Liman, tekneler ve renkli cepheler; Marsilya’nın kalbi.', t: 'Paysage' },
      en: { n: 'Old Port', d: 'The harbour, boats and colourful façades, the heart of Marseille.', t: 'Landscape' },
      fr: { n: 'Vieux-Port', d: 'Le port, les bateaux et les façades colorées, cœur de Marseille.', t: 'Paysage' } },
    { id: 'marseille-herbes', coll: 'marseille', img: 'items/ChatGPT%20Image%208%20Tem%202026%2013_51_48.jpg',
      tr: { n: 'Herbes de Provence', d: 'Lavanta ve biberiye dalları; Provence botanik deseni.', t: 'Nature' },
      en: { n: 'Provence Herbs', d: 'Lavender and rosemary sprigs, a Provençal botanical pattern.', t: 'Nature' },
      fr: { n: 'Herbes de Provence', d: 'Branches de lavande et de romarin, motif botanique provençal.', t: 'Nature' } },

    /* FORT BOYARD */
    { id: 'fortboyard-fort', coll: 'fortboyard', img: 'items/ChatGPT%20Image%208%20Tem%202026%2013_49_26.jpg',
      tr: { n: 'Fort Boyard', d: 'Denizin ortasında taş kale, dalgalar ve üç kuş.', t: 'Monument' },
      en: { n: 'Fort Boyard', d: 'A stone fortress in the sea, waves and three birds.', t: 'Monument' },
      fr: { n: 'Fort Boyard', d: 'Une forteresse de pierre en mer, vagues et trois oiseaux.', t: 'Monument' } },
    { id: 'fortboyard-vue', coll: 'fortboyard', img: 'items/ChatGPT%20Image%208%20Tem%202026%2013_49_29.jpg',
      tr: { n: 'Fort Boyard — Vue', d: 'Kalenin önden görünümü, kule ve dalgalı deniz.', t: 'Paysage' },
      en: { n: 'Fort Boyard — View', d: 'The fortress in front view, tower and rolling sea.', t: 'Landscape' },
      fr: { n: 'Fort Boyard — Vue', d: 'La forteresse de face, tour et mer ondulée.', t: 'Paysage' } }
  ];

  const I18N = {
    tr: {
      skip: 'İçeriğe atla',
      'nav.collections': 'Koleksiyonlar', 'nav.catalog': 'Katalog', 'nav.atelier': 'Atölye',
      'nav.contact': 'İletişim', 'nav.quote': 'Teklif Al',
      'hero.eyebrow': 'NICE · FRANSA · 1976’DAN BERİ',
      'hero.title1': 'Riviera’nın kumaşları,', 'hero.title2': 'nakışla dokunmuş anıları.',
      'hero.lede': 'Turistik tekstilin toptan üreticisi. Her desen, Fransız kıyılarının bir köşesini keten üzerine işler; otelinize, mağazanıza ve misafirlerinize taşınmak üzere.',
      'hero.cta1': 'Koleksiyonları İncele', 'hero.cta2': 'Numune & Fiyat Teklifi',
      'hero.note': 'B2B · Min. sipariş: 100 adet / desen · Tüm Avrupa’ya teslimat',
      'hero.caption': '“Monte-Carlo” — Damira Atölye nakışı, %100 keten',
      'collections.eyebrow': 'KOLEKSİYONLAR', 'collections.title': 'Bir bölge, bir hikâye, bir dizi desen.',
      'collections.lede': 'Her koleksiyon, Fransız kıyılarının bir köşesinden ilham alır. Koleksiyonları seçin, kataloğu filtreleyin.',
      'catalog.eyebrow': 'KATALOG', 'catalog.title': 'Desenler',
      'catalog.searchLabel': 'Desen ara', 'catalog.searchPh': 'Desen ara…',
      'catalog.empty': 'Bu filtreye uyan desen yok. Başka bir koleksiyon deneyin.',
      'catalog.more': 'Daha Fazla Desen', 'catalog.all': 'Tümü',
      'modal.inQuote': 'Teklife Eklendi', 'modal.remove': 'Tekliften çıkar',
      'atelier.eyebrow': 'ATÖLYE', 'atelier.title': 'Dokunuşu hissettiren kumaş.',
      'atelier.lede': 'Keten, pamuk ve keten-pamuk karışımları; elle yönlendirilen makine nakışı. Her desen, renk haslığı ve aşınma direnci testlerinden geçer.',
      'atelier.f1': '%100 Keten', 'atelier.f1d': 'Dokuma: 210 g/m², doğal yıkamalı',
      'atelier.f2': 'Nakış', 'atelier.f2d': '38.000 dikiş / desen, saten dolgu',
      'atelier.f3': 'Özel Üretim', 'atelier.f3d': 'Kendi motifinizi sipariş edin',
      'atelier.link': 'Özel üretim için bize yazın →',
      'contact.eyebrow': 'TEKLİF & İLETİŞİM', 'contact.title': 'Bir teklif alın.',
      'contact.lede': 'Desenleri seçin, formu doldurun; fiyat listesi ve numune programı iki iş günü içinde yanınızda.',
      'contact.addr': '12, Avenue de la Californie, 06200 Nice, France',
      'form.selected': 'Teklife eklenen desenler', 'form.noSelection': 'Henüz desen seçilmedi. Katalogları inceleyin.',
      'form.name': 'Ad Soyad *', 'form.company': 'Firma', 'form.email': 'E-posta *', 'form.phone': 'Telefon',
      'form.message': 'Mesaj', 'form.messagePh': 'İhtiyaç duyduğunuz miktar, renk, teslim tarihi…',
      'form.error': 'Lütfen zorunlu alanları doldurun: ad ve geçerli bir e-posta.',
      'form.submit': 'Teklif Talebi Gönder', 'form.sending': 'Gönderiliyor…',
      'form.success': 'Talebiniz alındı. En geç 2 iş günü içinde size dönüş yapacağız.',
      'footer.note': 'Nice, Fransa · 1976’dan beri turistik tekstil üretimi',
      'modal.addQuote': 'Teklife Ekle', 'modal.pdf': 'PDF Kataloğu İndir',
      'modal.specs': 'Dokuma', 'modal.specsV': '%100 keten · 210 g/m² · 38.000 dikiş',
      'modal.unit': 'adet'
    },
    en: {
      skip: 'Skip to content',
      'nav.collections': 'Collections', 'nav.catalog': 'Catalog', 'nav.atelier': 'Atelier',
      'nav.contact': 'Contact', 'nav.quote': 'Get a Quote',
      'hero.eyebrow': 'NICE · FRANCE · SINCE 1976',
      'hero.title1': 'Fabrics of the Riviera,', 'hero.title2': 'memories stitched in thread.',
      'hero.lede': 'Wholesale producer of tourist textiles. Every design embroiders a corner of the French coast onto linen, ready for your hotel, your store and your guests.',
      'hero.cta1': 'Browse Collections', 'hero.cta2': 'Samples & Pricing',
      'hero.note': 'B2B · Min. order: 100 pcs / design · Delivery across Europe',
      'hero.caption': '“Monte-Carlo” — Damira Atelier embroidery, 100% linen',
      'collections.eyebrow': 'COLLECTIONS', 'collections.title': 'One region, one story, one series of designs.',
      'collections.lede': 'Each collection draws from a corner of the French coast. Pick a collection to filter the catalog.',
      'catalog.eyebrow': 'CATALOG', 'catalog.title': 'Designs',
      'catalog.searchLabel': 'Search designs', 'catalog.searchPh': 'Search designs…',
      'catalog.empty': 'No designs match this filter. Try another collection.',
      'catalog.more': 'Load More Designs', 'catalog.all': 'All',
      'modal.inQuote': 'Added to Quote', 'modal.remove': 'Remove from quote',
      'atelier.eyebrow': 'ATELIER', 'atelier.title': 'Fabric you can feel.',
      'atelier.lede': 'Linen, cotton and linen-cotton blends, machine embroidery guided by hand. Every design passes colour-fastness and abrasion tests.',
      'atelier.f1': '100% Linen', 'atelier.f1d': 'Weave: 210 g/m², garment-washed',
      'atelier.f2': 'Embroidery', 'atelier.f2d': '38,000 stitches / design, satin fill',
      'atelier.f3': 'Custom Production', 'atelier.f3d': 'Order your own motif',
      'atelier.link': 'Write to us about custom production →',
      'contact.eyebrow': 'QUOTE & CONTACT', 'contact.title': 'Request a quote.',
      'contact.lede': 'Select designs, fill the form; pricing and a sample program reach you within two working days.',
      'contact.addr': '12, Avenue de la Californie, 06200 Nice, France',
      'form.selected': 'Designs added to the quote', 'form.noSelection': 'No designs selected yet. Browse the catalog.',
      'form.name': 'Full name *', 'form.company': 'Company', 'form.email': 'Email *', 'form.phone': 'Phone',
      'form.message': 'Message', 'form.messagePh': 'Quantities, colours, delivery dates…',
      'form.error': 'Please complete the required fields: name and a valid email.',
      'form.submit': 'Send Quote Request', 'form.sending': 'Sending…',
      'form.success': 'Request received. We will reply within two working days.',
      'footer.note': 'Nice, France · tourist textile production since 1976',
      'modal.addQuote': 'Add to Quote', 'modal.pdf': 'Download PDF Catalog',
      'modal.specs': 'Weave', 'modal.specsV': '100% linen · 210 g/m² · 38,000 stitches',
      'modal.unit': 'pcs'
    },
    fr: {
      skip: 'Aller au contenu',
      'nav.collections': 'Collections', 'nav.catalog': 'Catalogue', 'nav.atelier': 'Atelier',
      'nav.contact': 'Contact', 'nav.quote': 'Demander un devis',
      'hero.eyebrow': 'NICE · FRANCE · DEPUIS 1976',
      'hero.title1': 'Les tissus de la Riviera,', 'hero.title2': 'des souvenirs brodés au fil.',
      'hero.lede': 'Producteur en gros de textiles touristiques. Chaque motif brode un coin de la côte française sur du lin, prêt pour votre hôtel, votre boutique et vos clients.',
      'hero.cta1': 'Voir les collections', 'hero.cta2': 'Échantillons & tarifs',
      'hero.note': 'B2B · Commande min. : 100 pcs / motif · Livraison dans toute l’Europe',
      'hero.caption': '« Monte-Carlo » — broderie de l’Atelier Damira, 100 % lin',
      'collections.eyebrow': 'COLLECTIONS', 'collections.title': 'Une région, une histoire, une série de motifs.',
      'collections.lede': 'Chaque collection s’inspire d’un coin de la côte française. Choisissez une collection pour filtrer le catalogue.',
      'catalog.eyebrow': 'CATALOGUE', 'catalog.title': 'Motifs',
      'catalog.searchLabel': 'Rechercher des motifs', 'catalog.searchPh': 'Rechercher des motifs…',
      'catalog.empty': 'Aucun motif ne correspond à ce filtre. Essayez une autre collection.',
      'catalog.more': 'Voir plus de motifs', 'catalog.all': 'Tous',
      'modal.inQuote': 'Ajouté au devis', 'modal.remove': 'Retirer du devis',
      'atelier.eyebrow': 'ATELIER', 'atelier.title': 'Un tissu qui se ressent.',
      'atelier.lede': 'Lin, coton et mélanges lin-coton, broderie machine guidée à la main. Chaque motif passe des tests de solidité des couleurs et d’usure.',
      'atelier.f1': '100 % Lin', 'atelier.f1d': 'Tissage : 210 g/m², lavé en bain',
      'atelier.f2': 'Broderie', 'atelier.f2d': '38 000 points / motif, remplissage satin',
      'atelier.f3': 'Fabrication sur mesure', 'atelier.f3d': 'Commandez votre propre motif',
      'atelier.link': 'Écrivez-nous pour une production sur mesure →',
      'contact.eyebrow': 'DEVIS & CONTACT', 'contact.title': 'Demandez un devis.',
      'contact.lede': 'Choisissez vos motifs, remplissez le formulaire ; tarifs et programme d’échantillons sous deux jours ouvrés.',
      'contact.addr': '12, avenue de la Californie, 06200 Nice, France',
      'form.selected': 'Motifs ajoutés au devis', 'form.noSelection': 'Aucun motif sélectionné. Parcourez le catalogue.',
      'form.name': 'Nom complet *', 'form.company': 'Société', 'form.email': 'E-mail *', 'form.phone': 'Téléphone',
      'form.message': 'Message', 'form.messagePh': 'Quantités, couleurs, délais de livraison…',
      'form.error': 'Merci de remplir les champs obligatoires : nom et e-mail valide.',
      'form.submit': 'Envoyer la demande de devis', 'form.sending': 'Envoi en cours…',
      'form.success': 'Demande reçue. Réponse sous deux jours ouvrés.',
      'footer.note': 'Nice, France · production de textiles touristiques depuis 1976',
      'modal.addQuote': 'Ajouter au devis', 'modal.pdf': 'Télécharger le catalogue PDF',
      'modal.specs': 'Tissage', 'modal.specsV': '100 % lin · 210 g/m² · 38 000 points',
      'modal.unit': 'pcs'
    }
  };

  global.DAMIRA = { COLLECTIONS, PRODUCTS, I18N };
})(window);
