/* DAMIRA TEXTILE — veri katmanı
 * Yeni koleksiyon eklemek: COLLECTIONS'a kayıt, DESENLER'e img + çeviriler.
 * Görseller items/<koleksiyon>/ klasörlerindedir; filtre/arama otomatik çalışır.
 * ratio: görselin native oranı (w/h) — kesilmeden gösterim için.
 */
(function (global) {
  'use strict';

  const COLLECTIONS = [
    { id: 'monaco',    img: 'items/monaco/ChatGPT%20Image%2029%20Tem%202026%2012_26_41.jpg', ratio: 960/768, tr: 'Monaco',    en: 'Monaco',    fr: 'Monaco' },
    { id: 'corsica',   img: 'items/corsica/ChatGPT%20Image%206%20Tem%202026%2014_11_22.jpg', ratio: 1, tr: 'Korsika',   en: 'Corsica',   fr: 'Corse' },
    { id: 'vendee',    img: 'items/vendee/ChatGPT%20Image%2030%20Tem%202026%2012_37_07.jpg', ratio: 1, tr: 'Vendée',    en: 'Vendée',    fr: 'Vendée' },
    { id: 'oleron',    img: 'items/ile%20doleron/ChatGPT%20Image%2029%20Tem%202026%2015_24_04.jpg', ratio: 896/768, tr: 'Île d’Oléron', en: 'Île d’Oléron', fr: 'Île d’Oléron' },
    { id: 'baiedesomme', img: 'items/baie%20de%20somme/ChatGPT%20Image%2030%20Tem%202026%2012_41_28.jpg', ratio: 1024/768, tr: 'Baie de Somme', en: 'Baie de Somme', fr: 'Baie de Somme' },
    { id: 'marseille', img: 'items/marseille/ChatGPT%20Image%208%20Tem%202026%2013_49_26.jpg', ratio: 684/768, tr: 'Marsilya',  en: 'Marseille', fr: 'Marseille' },
    { id: 'fortboyard', img: 'items/ford%20boyard/ChatGPT%20Image%2030%20Tem%202026%2012_19_07.jpg', ratio: 1, tr: 'Fort Boyard', en: 'Fort Boyard', fr: 'Fort Boyard' }
  ];

  /* Desenler: koleksiyon id'si + görsel yolu + dillerde (ad, açıklama, etiket) + ratio. */
  const PRODUCTS = [
    /* MONACO */
    { id: 'monaco-casino', coll: 'monaco', img: 'items/monaco/ChatGPT%20Image%2029%20Tem%202026%2012_26_41.jpg', ratio: 960/768,
      tr: { n: 'Monte-Carlo', d: 'Kumarhanenin Beaux-Arts cephesi, kubbeli kuleleri ve çan kuleleri; önünde katmanlı çeşme, palmiyeler ve fener direkleri. Altın, lacivert ve zümrüt tonlarında, gece ışıltısını çağrıştıran simetrik bir kompozisyon.', t: 'Monument' },
      en: { n: 'Monte-Carlo', d: 'The Beaux-Arts casino façade with domed towers and clocks; a tiered fountain, palms and lampposts in front. A symmetrical composition in gold, navy and emerald, evoking a dusk glow.', t: 'Monument' },
      fr: { n: 'Monte-Carlo', d: 'La façade Beaux-Arts du casino, ses tours à coupoles et ses horloges ; fontaine en cascade, palmiers et lampadaires au premier plan. Composition symétrique or, marine et émeraude.', t: 'Monument' } },
    { id: 'monaco-port', coll: 'monaco', img: 'items/monaco/ChatGPT%20Image%2029%20Tem%202026%2012_30_02.jpg', ratio: 576/768,
      tr: { n: 'Port Hercule', d: 'Taş korkuluklu bir terastan limana bakış: dövme demir fener, bembeyaz yatlar, terakota çatılı evler ve ufukta mavi dağlar. Lacivert denizin üzerinde dingin bir Akdeniz sabahı.', t: 'Paysage' },
      en: { n: 'Port Hercule', d: 'A terrace view over the harbour: a wrought-iron lantern, gleaming white yachts, terracotta-roofed houses and blue hills on the horizon. A calm Mediterranean morning over a navy sea.', t: 'Landscape' },
      fr: { n: 'Port Hercule', d: 'Vue en terrasse sur le port : lanterne en fer forgé, yachts blancs éclatants, maisons aux toits de terracotta et collines bleues à l’horizon. Matin calme sur une mer marine.', t: 'Paysage' } },
    { id: 'monaco-palais', coll: 'monaco', img: 'items/monaco/ChatGPT%20Image%2029%20Tem%202026%2012_34_37.jpg', ratio: 960/768,
      tr: { n: 'Palais Princier', d: 'Prens Sarayı’nın kum rengi cephesi, gri mazgallı kuleleri ve kırmızı çatılı muhafız kulübeleri; arkasında yükselen yeşil dağ ve önünde arnavut kaldırımlı meydan. Tarihi taş dokusu ve Akdeniz ışığı.', t: 'Monument' },
      en: { n: 'Prince’s Palace', d: 'The sandy-yellow palace façade with grey crenellated towers and red-roofed guardhouses; a green mountain rising behind and a cobbled square in front. Historic stone texture in Mediterranean light.', t: 'Monument' },
      fr: { n: 'Palais Princier', d: 'La façade sable du palais, ses tours grises crénelées et ses corps de garde aux toits rouges ; montagne verte en arrière-plan et place pavée devant. Pierre historique sous la lumière méditerranéenne.', t: 'Monument' } },
    { id: 'monaco-terrasse', coll: 'monaco', img: 'items/monaco/ChatGPT%20Image%2029%20Tem%202026%2012_37_58.jpg', ratio: 1,
      tr: { n: 'Jardin Exotique', d: 'Lavanta çalılarıyla çevrili bir bahçe terası: taş kemer, servi ve çam ağaçları, zeytin ağacı; ileride denize uzanan kıyı ve tepede bayraklı saray. Mor, zümrüt ve lacivertin huzurlu buluşması.', t: 'Jardin' },
      en: { n: 'Exotic Garden', d: 'A garden terrace framed by lavender: a stone arch, cypress and pine trees, an olive tree; the coast stretching to the sea with a flag-topped palace on the hill. A peaceful meeting of violet, emerald and navy.', t: 'Garden' },
      fr: { n: 'Jardin Exotique', d: 'Terrasse de jardin encadrée de lavande : arche en pierre, cyprès et pins, olivier ; la côte vers la mer et le palais à drapeau sur la colline. Rencontre paisible de violet, d’émeraude et de marine.', t: 'Jardin' } },

    /* CORSICA */
    { id: 'corsica-moor', coll: 'corsica', img: 'items/corsica/ChatGPT%20Image%206%20Tem%202026%2011_49_58.jpg', ratio: 960/768,
      tr: { n: 'Testa Mora', d: 'Korsika’nın simgesi Mağribi başı: alnında beyaz bant, arkada sarkan uçlarıyla. Siyah-beyaz yüksek kontrast, saten dikişin kabartmalı dokusu; zamansız ve cesur bir amblem.', t: 'Emblème' },
      en: { n: 'Testa Mora', d: 'The Moor’s head, Corsica’s emblem: a white band across the brow with its ends trailing behind. High-contrast black and white with raised satin stitch; a timeless, bold emblem.', t: 'Emblem' },
      fr: { n: 'Testa Mora', d: 'La tête de Maure, emblème de la Corse : bandeau blanc sur le front aux pans flottants. Contraste noir et blanc, point satin en relief ; emblème intemporel et affirmé.', t: 'Emblème' } },
    { id: 'corsica-olives', coll: 'corsica', img: 'items/corsica/ChatGPT%20Image%206%20Tem%202026%2012_03_20.jpg', ratio: 1,
      tr: { n: 'Olivier', d: 'Sapıyla birlikte taşan bir hasır sepette siyah ve yeşil zeytinler; sepetin dışında birkaç zeytin ve yaprak. Koyu yeşil, zeytin ve kahvenin toprak tonlarında bereketli bir natürmort.', t: 'Nature' },
      en: { n: 'Olive Grove', d: 'Black and green olives spilling from a woven wicker basket, a few olives and a leaf resting outside. An abundant still life in earthy greens, olives and browns.', t: 'Nature' },
      fr: { n: 'Olivier', d: 'Olives noires et vertes débordant d’un panier en osier tressé, quelques olives et une feuille posées à côté. Nature morte généreuse aux tons verts, olives et bruns.', t: 'Nature' } },
    { id: 'corsica-bonifacio', coll: 'corsica', img: 'items/corsica/ChatGPT%20Image%206%20Tem%202026%2014_05_24.jpg', ratio: 1,
      tr: { n: 'Bonifacio', d: 'Sarp kayalıkların üzerinde terakota çatılı evler ve bir çan kulesi; solda yatay dikişlerle işlenmiş deniz, sağda zeytin dalı. Korsika kıyılarının sakin ve zarif hali.', t: 'Paysage' },
      en: { n: 'Bonifacio', d: 'Terracotta-roofed houses and a bell tower perched on steep cliffs; the sea stitched in horizontal lines to the left, an olive branch to the right. Corsica’s coast, serene and elegant.', t: 'Landscape' },
      fr: { n: 'Bonifacio', d: 'Maisons aux toits de terracotta et clocher sur des falaises abruptes ; mer en points horizontaux à gauche, branche d’olivier à droite. La côte corse, sereine et élégante.', t: 'Paysage' } },
    { id: 'corsica-tour', coll: 'corsica', img: 'items/corsica/ChatGPT%20Image%206%20Tem%202026%2014_11_22.jpg', ratio: 1,
      tr: { n: 'Tour Génoise', d: 'Ceneviz kulesi: mazgallı, yuvarlak taş gövde, kayalık zemin ve yeşillik; ufukta tek bir deniz çizgisi, gökte süzülen bir kuş ve sağda zeytin dalı. Sade, arketipsel bir Akdeniz manzarası.', t: 'Monument' },
      en: { n: 'Genoese Tower', d: 'A Genoese tower: crenellated round stone body on a rocky, grassy base; a single sea line on the horizon, one bird in flight, an olive branch to the right. A simple, archetypal Mediterranean view.', t: 'Monument' },
      fr: { n: 'Tour Génoise', d: 'Une tour génoise : corps de pierre rond crénelé sur un socle rocheux et herbeux ; un trait de mer à l’horizon, un oiseau en vol, branche d’olivier à droite. Vue méditerranéenne simple et archétypale.', t: 'Monument' } },
    { id: 'corsica-citrons', coll: 'corsica', img: 'items/corsica/ChatGPT%20Image%206%20Tem%202026%2014_37_21.jpg', ratio: 1,
      tr: { n: 'Citronniers', d: 'Hasır sepetin içinde parlak sarı limonlar, aralarında koyu yeşil yapraklar ve beyaz çiçekler; sepetin yanında dördüncü bir limon. Güneşle yıkanmış narenciye bahçelerinin neşesi.', t: 'Nature' },
      en: { n: 'Lemon Grove', d: 'Bright yellow lemons in a wicker basket among dark green leaves and white blossoms, a fourth lemon resting beside it. The cheer of sun-washed citrus groves.', t: 'Nature' },
      fr: { n: 'Citronniers', d: 'Citrons jaune vif dans un panier en osier parmi des feuilles vert foncé et des fleurs blanches, un quatrième citron posé à côté. La gaieté des vergers baignés de soleil.', t: 'Nature' } },

    /* VENDÉE */
    { id: 'vendee-embleme', coll: 'vendee', img: 'items/vendee/615a8aa1-5dd5-4beb-8635-6495e98719b2.jpg', ratio: 1,
      tr: { n: 'Emblème Vendéen', d: 'Kurdele benzeri kıvrımların birleştiği stilize kalp formu, tepesinde haç detayı; tek renk kırmızı saten dikişle işlenmiş. Beyaz kumaş üzerinde güçlü ve zarif bir bölgesel amblem.', t: 'Emblème' },
      en: { n: 'Vendée Emblem', d: 'A stylised heart formed by ribbon-like curves, topped with a cross detail, worked in a single red satin stitch. A strong, elegant regional emblem on white fabric.', t: 'Emblem' },
      fr: { n: 'Emblème Vendéen', d: 'Cœur stylisé formé de courbes en ruban, surmonté d’une croix, brodé d’un seul fil rouge satin. Emblème régional fort et élégant sur tissu blanc.', t: 'Emblème' } },
    { id: 'vendee-fenetre', coll: 'vendee', img: 'items/vendee/ChatGPT%20Image%2030%20Tem%202026%2012_32_00.jpg', ratio: 1,
      tr: { n: 'La Fenêtre', d: 'Mavi panjurlu bir pencere, beyaz perdeler ve kırmızı çiçekli bir pencere kutusu; altında çiçek dolu hasır sepetli mavi bir bisiklet. Fransız kırsalının nostaljik bir köşesi.', t: 'Scène' },
      en: { n: 'The Window', d: 'A window with blue shutters, white curtains and a flower box of red blooms; below, a blue bicycle with a wicker basket full of flowers. A nostalgic corner of the French countryside.', t: 'Scene' },
      fr: { n: 'La Fenêtre', d: 'Fenêtre aux volets bleus, rideaux blancs et jardinière de fleurs rouges ; dessous, un vélo bleu au panier d’osier fleuri. Un coin nostalgique de la campagne française.', t: 'Scène' } },
    { id: 'vendee-poissons', coll: 'vendee', img: 'items/vendee/ChatGPT%20Image%2030%20Tem%202026%2012_37_07.jpg', ratio: 1,
      tr: { n: 'Trois Poissons', d: 'Dikey dizilmiş üç stilize balık: lacivert, kırmızı ve turkuaz; her biri yatay çizgili gövde ve nokta gözlü. Temiz, denizci bir amblem — Vendée kıyılarının simgesi.', t: 'Marin' },
      en: { n: 'Three Fishes', d: 'Three stylised fishes stacked vertically in navy, red and turquoise, each with a striped body and dot eye. A crisp nautical emblem of the Vendée coast.', t: 'Marine' },
      fr: { n: 'Trois Poissons', d: 'Trois poissons stylisés empilés en marine, rouge et turquoise, chacun au corps rayé et à l’œil point. Emblème marin net de la côte vendéenne.', t: 'Marin' } },
    { id: 'vendee-goeland', coll: 'vendee', img: 'items/vendee/ChatGPT%20Image%2030%20Tem%202026%2012_38_22.jpg', ratio: 1,
      tr: { n: 'Goéland', d: 'Ahşap bir kazık üzerinde duran martı; beyaz baş, gri kanatlar, sarı gaga. Arkada dalgalı deniz, kumlu sahil ve yeşil kıyı otları. Denizin nefesini hissettiren sakin bir sahne.', t: 'Marin' },
      en: { n: 'Seagull', d: 'A gull perched on a wooden post, white head, grey wings, yellow beak; rolling sea, sandy shore and green beach grass behind. A calm scene that carries the breath of the sea.', t: 'Marine' },
      fr: { n: 'Goéland', d: 'Goéland posé sur un poteau de bois, tête blanche, ailes grises, bec jaune ; mer ondulée, plage de sable et herbes vertes derrière. Scène paisible qui porte le souffle de la mer.', t: 'Marin' } },

    /* ÎLE D'OLÉRON */
    { id: 'oleron-carrelets', coll: 'oleron', img: 'items/ile%20doleron/ChatGPT%20Image%2029%20Tem%202026%2015_24_04.jpg', ratio: 896/768,
      tr: { n: 'Carrelets', d: 'Ahşap iskele üzerinde üç renkli balıkçı kulübesi — mavi, çikolata kahvesi ve turkuaz; terakota çatılar, önünde beyaz bir kayık. Oléron’un deniz üstündeki simgesel kulübeleri.', t: 'Paysage' },
      en: { n: 'Fishing Huts', d: 'Three colourful fishing huts on a wooden pier — blue, chocolate brown and turquoise with terracotta roofs, a white rowboat in front. The iconic on-stilts huts of Oléron.', t: 'Landscape' },
      fr: { n: 'Carrelets', d: 'Trois cabanes de pêcheurs colorées sur pilotis — bleu, brun chocolat et turquoise aux toits de terracotta, une barque blanche devant. Les cabanes emblématiques d’Oléron.', t: 'Paysage' } },
    { id: 'oleron-phare', coll: 'oleron', img: 'items/ile%20doleron/ChatGPT%20Image%2029%20Tem%202026%2015_27_43.jpg', ratio: 1,
      tr: { n: 'Phare de Chassiron', d: 'Kırmızı fenerli ve korkuluklu beyaz deniz feneri, yuvarlak taş kaide üzerinde; arkada yatay dikişlerle işlenmiş mavi deniz. Oléron’un en tanınmış silueti.', t: 'Monument' },
      en: { n: 'Chassiron Lighthouse', d: 'A white lighthouse with a red lantern room and railing on a round stone base, a blue sea stitched in horizontal bands behind. Oléron’s most recognisable silhouette.', t: 'Monument' },
      fr: { n: 'Phare de Chassiron', d: 'Phare blanc au feu et à la rambarde rouges sur un socle de pierre rond, mer bleue en bandes horizontales derrière. La silhouette la plus connue d’Oléron.', t: 'Monument' } },
    { id: 'oleron-poissons', coll: 'oleron', img: 'items/ile%20doleron/ChatGPT%20Image%2029%20Tem%202026%2015_31_42.jpg', ratio: 1,
      tr: { n: 'Poissons d’Oléron', d: 'Üç stilize balık: lacivert, kırmızı ve açık mavi; gövde çizgileri ve nokta gözlerle sade bir çizim. Kavisli yazıyla birlikte neşeli ve denizci bir desen.', t: 'Marin' },
      en: { n: 'Oléron Fishes', d: 'Three stylised fishes in navy, red and light blue, drawn simply with body lines and dot eyes. A cheerful nautical pattern with curved lettering.', t: 'Marine' },
      fr: { n: 'Poissons d’Oléron', d: 'Trois poissons stylisés marine, rouge et bleu clair, au dessin simple avec lignes et œil point. Motif marin joyeux aux lettres incurvées.', t: 'Marin' } },
    { id: 'oleron-bicyclette', coll: 'oleron', img: 'items/ile%20doleron/ChatGPT%20Image%2030%20Tem%202026%2010_47_05.jpg', ratio: 1,
      tr: { n: 'Bicyclette Fleurie', d: 'Mavi panjurlu bir pencerenin altında sarı bir bisiklet; gidonunda pembe çiçeklerle dolu hasır sepet. Oléron köylerinin sıcak, yazlık hali — pastel ve neşeli.', t: 'Scène' },
      en: { n: 'Flowered Bicycle', d: 'A yellow bicycle beneath a window with blue shutters, its basket brimming with pink flowers. The warm, summery spirit of Oléron villages — pastel and cheerful.', t: 'Scene' },
      fr: { n: 'Bicyclette Fleurie', d: 'Un vélo jaune sous une fenêtre aux volets bleus, son panier débordant de fleurs roses. L’esprit estival et chaleureux des villages d’Oléron — pastel et joyeux.', t: 'Scène' } },

    /* BAIE DE SOMME */
    { id: 'somme-cabanes', coll: 'baiedesomme', img: 'items/baie%20de%20somme/ChatGPT%20Image%2030%20Tem%202026%2012_41_28.jpg', ratio: 1024/768,
      tr: { n: 'Cabanes de Plage', d: 'Ahşap iskele üzerinde üç plaj kulübesi — mavi, kahve ve turkuaz, terakota çatılı; ön planda bir martı. Baie de Somme’un rengarenk sahil kulübeleri.', t: 'Scène' },
      en: { n: 'Beach Huts', d: 'Three beach huts on a wooden boardwalk — blue, brown and turquoise with terracotta roofs, a gull in the foreground. The colourful seaside huts of the Baie de Somme.', t: 'Scene' },
      fr: { n: 'Cabanes de Plage', d: 'Trois cabanes de plage sur pilotis — bleu, brun et turquoise aux toits de terracotta, un goéland au premier plan. Les cabanes colorées de la baie de Somme.', t: 'Scène' } },
    { id: 'somme-cabanes-4', coll: 'baiedesomme', img: 'items/baie%20de%20somme/ChatGPT%20Image%2030%20Tem%202026%2012_41_39.jpg', ratio: 1024/683,
      tr: { n: 'Quatre Cabanes', d: 'Dalgaların üzerinde yan yana dört plaj kulübesi: beyaz, açık mavi, kırmızı-beyaz çizgili ve turkuaz; üzerlerinde süzülen bir martı. Yaz tatilinin özeti.', t: 'Scène' },
      en: { n: 'Four Huts', d: 'Four beach huts in a row above the waves — white, light blue, red-and-white striped and turquoise — with a gull flying above. A summary of summer holidays.', t: 'Scene' },
      fr: { n: 'Quatre Cabanes', d: 'Quatre cabanes de plage alignées sur les vagues — blanche, bleu clair, rayée rouge et blanc, turquoise — avec un goéland en vol. Le résumé des vacances d’été.', t: 'Scène' } },
    { id: 'somme-phoque', coll: 'baiedesomme', img: 'items/baie%20de%20somme/ChatGPT%20Image%2030%20Tem%202026%2012_46_13.jpg', ratio: 1,
      tr: { n: 'Phoque', d: 'Kumda yan yatmış, yüzgecini kaldırmış benekli bir fok; arkada yatay çizgilerle deniz, altta kum katmanları. Baie de Somme’un yaban hayatına sevecen bir selam.', t: 'Nature' },
      en: { n: 'The Seal', d: 'A spotted seal lying on the sand with a flipper raised, the sea stitched in horizontal lines behind and layers of shore below. A fond nod to the wildlife of the Baie de Somme.', t: 'Nature' },
      fr: { n: 'Phoque', d: 'Phoque tacheté couché sur le sable, nageoire levée, mer en lignes horizontales derrière et couches de plage dessous. Clin d’œil tendre à la faune de la baie de Somme.', t: 'Nature' } },
    { id: 'somme-poissons', coll: 'baiedesomme', img: 'items/baie%20de%20somme/ChatGPT%20Image%2030%20Tem%202026%2013_33_18.jpg', ratio: 1,
      tr: { n: 'Poissons de Somme', d: 'Sola yüzen üç stilize balık: lacivert konturlar, nokta gözler ve ince çizgili pullar. El çizimi zarafetinde, sade ve denizci bir desen.', t: 'Marin' },
      en: { n: 'Somme Fishes', d: 'Three stylised fishes swimming left in navy outlines with dot eyes and fine scale lines. A simple, nautical pattern with hand-drawn grace.', t: 'Marine' },
      fr: { n: 'Poissons de Somme', d: 'Trois poissons stylisés nageant vers la gauche, contours marine, œil point et fines écailles. Motif marin simple à la grâce dessinée à la main.', t: 'Marin' } },

    /* MARSEILLE */
    { id: 'marseille-basilique', coll: 'marseille', img: 'items/marseille/ChatGPT%20Image%208%20Tem%202026%2011_46_44.jpg', ratio: 614/768,
      tr: { n: 'Notre-Dame de la Garde', d: 'Tepede yükselen bazilika, altın Meryem heykeli ve çan kulesi; yumuşak sulu boya dokusunda bej, adaçayı yeşili ve altın tonları. Marsilya’nın koruyucusuna zarif bir saygı duruşu.', t: 'Monument' },
      en: { n: 'Notre-Dame de la Garde', d: 'The basilica rising on its hill with the golden Virgin and bell tower; soft watercolour texture in beige, sage and gold. An elegant tribute to Marseille’s guardian.', t: 'Monument' },
      fr: { n: 'Notre-Dame de la Garde', d: 'La basilique sur sa colline, Vierge dorée et clocher ; texture aquarelle douce en beige, sauge et or. Hommage élégant à la protectrice de Marseille.', t: 'Monument' } },
    { id: 'marseille-panorama', coll: 'marseille', img: 'items/marseille/ChatGPT%20Image%208%20Tem%202026%2013_49_26.jpg', ratio: 684/768,
      tr: { n: 'Panorama de Marseille', d: 'Liman manzaralı panoramik Marsilya: tepede Notre-Dame, yamaçta kırmızı çatılı beyaz evler, önde direkleriyle yelkenliler. Altın, okra ve terakotanın nostaljik buluşması.', t: 'Paysage' },
      en: { n: 'Marseille Panorama', d: 'A panoramic Marseille over the harbour: Notre-Dame on the hill, white houses with red roofs on the slopes, sailboats with tall masts in front. A nostalgic meeting of gold, ochre and terracotta.', t: 'Landscape' },
      fr: { n: 'Panorama de Marseille', d: 'Marseille panoramique sur le port : Notre-Dame sur la colline, maisons blanches aux toits rouges sur les pentes, voiliers à mâts devant. Rencontre nostalgique d’or, d’ocre et de terracotta.', t: 'Paysage' } },
    { id: 'marseille-herbes', coll: 'marseille', img: 'items/marseille/ChatGPT%20Image%208%20Tem%202026%2013_51_48.jpg', ratio: 614/768,
      tr: { n: 'Herbes de Provence', d: 'Lavanta dalları ve biberiye: mor çiçek başları, iğne yapraklar, odunsu gövde. Provence’ın kokusunu taşıyan, gerçekçi ve zarif bir botanik desen.', t: 'Nature' },
      en: { n: 'Provence Herbs', d: 'Lavender stalks and a rosemary sprig: purple flower heads, needle leaves, a woody stem. A realistic, elegant botanical pattern that carries the scent of Provence.', t: 'Nature' },
      fr: { n: 'Herbes de Provence', d: 'Tiges de lavande et brin de romarin : épis violets, feuilles en aiguilles, tige ligneuse. Motif botanique réaliste et élégant qui porte le parfum de la Provence.', t: 'Nature' } },

    /* FORT BOYARD */
    { id: 'fortboyard-fort', coll: 'fortboyard', img: 'items/ford%20boyard/ChatGPT%20Image%2030%20Tem%202026%2012_19_07.jpg', ratio: 1,
      tr: { n: 'Fort Boyard', d: 'Denizin ortasında yükselen taş kale: çizgili deniz feneri kulesi, sıra sıra koyu pencereler, kayalık kaide; gökte üç kuş. Nostaljik bir macera ve deniz hatırası.', t: 'Monument' },
      en: { n: 'Fort Boyard', d: 'A stone fortress rising from the sea: a striped lighthouse tower, rows of dark windows, a rocky base; three birds in the sky. A nostalgic souvenir of adventure and the sea.', t: 'Monument' },
      fr: { n: 'Fort Boyard', d: 'Forteresse de pierre surgissant de la mer : tour-phare rayée, rangées de fenêtres sombres, socle rocheux ; trois oiseaux dans le ciel. Souvenir nostalgique d’aventure et de mer.', t: 'Monument' } }
  ];

  const I18N = {
    tr: {
      skip: 'İçeriğe atla',
      'nav.collections': 'Koleksiyonlar', 'nav.catalog': 'Katalog', 'nav.atelier': 'Atölye',
      'nav.contact': 'İletişim', 'nav.quote': 'Teklif Al',
      'hero.eyebrow': 'NICE · FRANSA · 1976’DAN BERİ',
      'hero.title1': 'Riviera’nın kumaşları,', 'hero.title2': 'nakışla dokunmuş anıları.',
      'hero.lede': 'Turistik tekstilin toptan üreticisi. Her desen, Fransız kıyılarının bir köşesini keten üzerine işler; otelinize, mağazanıza ve misafirlerinize taşınmak üzere.',
      'hero.cta1': 'Koleksiyonları İncele', 'hero.cta2': 'Numune & Fiyat Teklifi',
      'hero.note': 'B2B · Min. sipariş: 100 adet / desen · Tüm Avrupa’ya teslimat',
      'hero.caption': '“Tour Génoise” — Damira Atölye nakışı, %100 keten',
      'collections.eyebrow': 'KOLEKSİYONLAR', 'collections.title': 'Bir bölge, bir hikâye, bir dizi desen.',
      'collections.lede': 'Her koleksiyon, Fransız kıyılarının bir köşesinden ilham alır. Koleksiyonları seçin, kataloğu filtreleyin.',
      'catalog.eyebrow': 'KATALOG', 'catalog.title': 'Desenler',
      'catalog.searchLabel': 'Desen ara', 'catalog.searchPh': 'Desen ara…',
      'catalog.empty': 'Bu filtreye uyan desen yok. Başka bir koleksiyon deneyin.',
      'catalog.more': 'Daha Fazla Desen', 'catalog.all': 'Tümü',
      'catalog.sortLabel': 'Sırala', 'catalog.sortName': 'İsim (A–Z)', 'catalog.sortColl': 'Koleksiyon', 'catalog.sortType': 'Tür',
      'catalog.reset': 'Filtreyi Temizle', 'catalog.count': 'desen',
      'modal.inQuote': 'Teklife Eklendi', 'modal.remove': 'Tekliften çıkar',
      'atelier.eyebrow': 'ATÖLYE', 'atelier.title': 'Dokunuşu hissettiren kumaş.',
      'atelier.lede': 'Keten, pamuk ve keten-pamuk karışımları; elle yönlendirilen makine nakışı. Her desen, renk haslığı ve aşınma direnci testlerinden geçer.',
      'atelier.f1': '%100 Keten', 'atelier.f1d': 'Dokuma: 210 g/m², doğal yıkamalı',
      'atelier.f2': 'Nakış', 'atelier.f2d': '38.000 dikiş / desen, saten dolgu',
      'atelier.f3': 'Özel Üretim', 'atelier.f3d': 'Kendi motifinizi sipariş edin',
      'atelier.link': 'Özel üretim için bize yazın →',
      'contact.eyebrow': 'TEKLİF & İLETİŞİM', 'contact.title': 'Bir teklif alın.',
      'contact.lede': 'Desenleri seçin, formu doldurun; fiyat listesi ve numune programı iki iş günü içinde yanınızda.',
      'contact.addr': '12, Avenue de la Californie, 06200 Nice, France',
      'form.selected': 'Teklife eklenen desenler', 'form.noSelection': 'Henüz desen seçilmedi. Katalogları inceleyin.',
      'form.name': 'Ad Soyad *', 'form.company': 'Firma', 'form.email': 'E-posta *', 'form.phone': 'Telefon',
      'form.message': 'Mesaj', 'form.messagePh': 'İhtiyaç duyduğunuz miktar, renk, teslim tarihi…',
      'form.error': 'Lütfen zorunlu alanları doldurun: ad ve geçerli bir e-posta.',
      'form.submit': 'Teklif Talebi Gönder', 'form.sending': 'Gönderiliyor…',
      'form.success': 'Talebiniz alındı. En geç 2 iş günü içinde size dönüş yapacağız.',
      'footer.note': 'Nice, Fransa · 1976’dan beri turistik tekstil üretimi',
      'modal.addQuote': 'Teklife Ekle', 'modal.pdf': 'PDF Kataloğu İndir',
      'modal.specs': 'Dokuma', 'modal.specsV': '%100 keten · 210 g/m² · 38.000 dikiş',
      'modal.unit': 'adet'
    },
    en: {
      skip: 'Skip to content',
      'nav.collections': 'Collections', 'nav.catalog': 'Catalog', 'nav.atelier': 'Atelier',
      'nav.contact': 'Contact', 'nav.quote': 'Get a Quote',
      'hero.eyebrow': 'NICE · FRANCE · SINCE 1976',
      'hero.title1': 'Fabrics of the Riviera,', 'hero.title2': 'memories stitched in thread.',
      'hero.lede': 'Wholesale producer of tourist textiles. Every design embroiders a corner of the French coast onto linen, ready for your hotel, your store and your guests.',
      'hero.cta1': 'Browse Collections', 'hero.cta2': 'Samples & Pricing',
      'hero.note': 'B2B · Min. order: 100 pcs / design · Delivery across Europe',
      'hero.caption': '“Genoese Tower” — Damira Atelier embroidery, 100% linen',
      'collections.eyebrow': 'COLLECTIONS', 'collections.title': 'One region, one story, one series of designs.',
      'collections.lede': 'Each collection draws from a corner of the French coast. Pick a collection to filter the catalog.',
      'catalog.eyebrow': 'CATALOG', 'catalog.title': 'Designs',
      'catalog.searchLabel': 'Search designs', 'catalog.searchPh': 'Search designs…',
      'catalog.empty': 'No designs match this filter. Try another collection.',
      'catalog.more': 'Load More Designs', 'catalog.all': 'All',
      'catalog.sortLabel': 'Sort', 'catalog.sortName': 'Name (A–Z)', 'catalog.sortColl': 'Collection', 'catalog.sortType': 'Type',
      'catalog.reset': 'Clear Filter', 'catalog.count': 'designs',
      'modal.inQuote': 'Added to Quote', 'modal.remove': 'Remove from quote',
      'atelier.eyebrow': 'ATELIER', 'atelier.title': 'Fabric you can feel.',
      'atelier.lede': 'Linen, cotton and linen-cotton blends, machine embroidery guided by hand. Every design passes colour-fastness and abrasion tests.',
      'atelier.f1': '100% Linen', 'atelier.f1d': 'Weave: 210 g/m², garment-washed',
      'atelier.f2': 'Embroidery', 'atelier.f2d': '38,000 stitches / design, satin fill',
      'atelier.f3': 'Custom Production', 'atelier.f3d': 'Order your own motif',
      'atelier.link': 'Write to us about custom production →',
      'contact.eyebrow': 'QUOTE & CONTACT', 'contact.title': 'Request a quote.',
      'contact.lede': 'Select designs, fill the form; pricing and a sample program reach you within two working days.',
      'contact.addr': '12, Avenue de la Californie, 06200 Nice, France',
      'form.selected': 'Designs added to the quote', 'form.noSelection': 'No designs selected yet. Browse the catalog.',
      'form.name': 'Full name *', 'form.company': 'Company', 'form.email': 'Email *', 'form.phone': 'Phone',
      'form.message': 'Message', 'form.messagePh': 'Quantities, colours, delivery dates…',
      'form.error': 'Please complete the required fields: name and a valid email.',
      'form.submit': 'Send Quote Request', 'form.sending': 'Sending…',
      'form.success': 'Request received. We will reply within two working days.',
      'footer.note': 'Nice, France · tourist textile production since 1976',
      'modal.addQuote': 'Add to Quote', 'modal.pdf': 'Download PDF Catalog',
      'modal.specs': 'Weave', 'modal.specsV': '100% linen · 210 g/m² · 38,000 stitches',
      'modal.unit': 'pcs'
    },
    fr: {
      skip: 'Aller au contenu',
      'nav.collections': 'Collections', 'nav.catalog': 'Catalogue', 'nav.atelier': 'Atelier',
      'nav.contact': 'Contact', 'nav.quote': 'Demander un devis',
      'hero.eyebrow': 'NICE · FRANCE · DEPUIS 1976',
      'hero.title1': 'Les tissus de la Riviera,', 'hero.title2': 'des souvenirs brodés au fil.',
      'hero.lede': 'Producteur en gros de textiles touristiques. Chaque motif brode un coin de la côte française sur du lin, prêt pour votre hôtel, votre boutique et vos clients.',
      'hero.cta1': 'Voir les collections', 'hero.cta2': 'Échantillons & tarifs',
      'hero.note': 'B2B · Commande min. : 100 pcs / motif · Livraison dans toute l’Europe',
      'hero.caption': '« Tour Génoise » — broderie de l’Atelier Damira, 100 % lin',
      'collections.eyebrow': 'COLLECTIONS', 'collections.title': 'Une région, une histoire, une série de motifs.',
      'collections.lede': 'Chaque collection s’inspire d’un coin de la côte française. Choisissez une collection pour filtrer le catalogue.',
      'catalog.eyebrow': 'CATALOGUE', 'catalog.title': 'Motifs',
      'catalog.searchLabel': 'Rechercher des motifs', 'catalog.searchPh': 'Rechercher des motifs…',
      'catalog.empty': 'Aucun motif ne correspond à ce filtre. Essayez une autre collection.',
      'catalog.more': 'Voir plus de motifs', 'catalog.all': 'Tous',
      'catalog.sortLabel': 'Trier', 'catalog.sortName': 'Nom (A–Z)', 'catalog.sortColl': 'Collection', 'catalog.sortType': 'Type',
      'catalog.reset': 'Effacer le filtre', 'catalog.count': 'motifs',
      'modal.inQuote': 'Ajouté au devis', 'modal.remove': 'Retirer du devis',
      'atelier.eyebrow': 'ATELIER', 'atelier.title': 'Un tissu qui se ressent.',
      'atelier.lede': 'Lin, coton et mélanges lin-coton, broderie machine guidée à la main. Chaque motif passe des tests de solidité des couleurs et d’usure.',
      'atelier.f1': '100 % Lin', 'atelier.f1d': 'Tissage : 210 g/m², lavé en bain',
      'atelier.f2': 'Broderie', 'atelier.f2d': '38 000 points / motif, remplissage satin',
      'atelier.f3': 'Fabrication sur mesure', 'atelier.f3d': 'Commandez votre propre motif',
      'atelier.link': 'Écrivez-nous pour une production sur mesure →',
      'contact.eyebrow': 'DEVIS & CONTACT', 'contact.title': 'Demandez un devis.',
      'contact.lede': 'Choisissez vos motifs, remplissez le formulaire ; tarifs et programme d’échantillons sous deux jours ouvrés.',
      'contact.addr': '12, avenue de la Californie, 06200 Nice, France',
      'form.selected': 'Motifs ajoutés au devis', 'form.noSelection': 'Aucun motif sélectionné. Parcourez le catalogue.',
      'form.name': 'Nom complet *', 'form.company': 'Société', 'form.email': 'E-mail *', 'form.phone': 'Téléphone',
      'form.message': 'Message', 'form.messagePh': 'Quantités, couleurs, délais de livraison…',
      'form.error': 'Merci de remplir les champs obligatoires : nom et e-mail valide.',
      'form.submit': 'Envoyer la demande de devis', 'form.sending': 'Envoi en cours…',
      'form.success': 'Demande reçue. Réponse sous deux jours ouvrés.',
      'footer.note': 'Nice, France · production de textiles touristiques depuis 1976',
      'modal.addQuote': 'Ajouter au devis', 'modal.pdf': 'Télécharger le catalogue PDF',
      'modal.specs': 'Tissage', 'modal.specsV': '100 % lin · 210 g/m² · 38 000 points',
      'modal.unit': 'pcs'
    }
  };

  global.DAMIRA = { COLLECTIONS, PRODUCTS, I18N };
})(window);
